name: Basic CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-and-test:
    name: Run Dev Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install Node dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Set up Python

        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Lint JS
        run: next lint
        continue-on-error: true

      - name: Lint Python
        run: |
          pip install black flake8
          black --check api/
          flake8 api/
        continue-on-error: true
